package com.atlas.ragengine.ingest;

import com.atlas.ragengine.common.PgVector;
import com.atlas.ragengine.ingest.DocumentChunker.Chunk;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Embeds chunks (nomic-embed-text 768, ADR-0005) and writes them to {@code atlas_chunk}.
 * The {@code content_tsv} sparse column is generated by Postgres on insert (see V1 migration).
 *
 * <p>Chunk ids are deterministic (name-based UUID from {@code documentId#index}) so a full
 * rebuild reproduces identical rows — stable citations + clean idempotency.
 */
public class EmbeddingWriter {

    private static final ObjectMapper JSON = new ObjectMapper();

    private final JdbcTemplate jdbc;
    private final EmbeddingModel embeddingModel;
    private final int dim;

    public EmbeddingWriter(JdbcTemplate jdbc, EmbeddingModel embeddingModel, int dim) {
        this.jdbc = jdbc;
        this.embeddingModel = embeddingModel;
        this.dim = dim;
    }

    /** Embeds and inserts every chunk of one document. Returns the number of chunks written. */
    public int write(UUID documentId, String clearance, Map<String, Object> baseMetadata, List<Chunk> chunks) {
        for (Chunk chunk : chunks) {
            float[] embedding = embeddingModel.embed(chunk.text());
            if (embedding.length != dim) {
                throw new IllegalStateException(
                        "Embedding dim " + embedding.length + " != expected " + dim
                                + " (check OLLAMA_EMBED_MODEL vs EMBED_DIM/ADR-0005)");
            }
            UUID chunkId = UUID.nameUUIDFromBytes((documentId + "#" + chunk.index()).getBytes());
            Map<String, Object> meta = new HashMap<>(baseMetadata);
            meta.put("chunkIndex", chunk.index());
            jdbc.update(
                    "INSERT INTO atlas_chunk "
                            + "(id, document_id, chunk_index, content, clearance, metadata, embedding) "
                            + "VALUES (?, ?, ?, ?, ?, ?::jsonb, ?::vector)",
                    chunkId, documentId, chunk.index(), chunk.text(), clearance,
                    toJson(meta), PgVector.toLiteral(embedding));
        }
        return chunks.size();
    }

    private static String toJson(Map<String, Object> meta) {
        try {
            return JSON.writeValueAsString(meta);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Failed to serialize chunk metadata", e);
        }
    }
}
